<?xml version="1.0" ?>
<robot name="camera" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find rob_lab_mapping)/urdf/rob_lab_items_mesurments.xacro" />
		
  
      <link name="world"/>

      
      <link name="camera_rail">
      <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
          <cylinder radius="${camera_rail_r}" length="${camera_rail_l}" />
        </geometry>
      </visual>
      <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
      ixx="0.0" ixy="0.0" ixz="0.0"
      iyy="0.0" iyz="0.0"
      izz="0.0"/>
      </inertial>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
          <cylinder radius="${camera_rail_r}" length="${camera_rail_l}" />
        </geometry>
      </collision>
      </link> 

        <!-- Camera -->
  <link name="camera_link">
    <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
          <box size="${camera_size*2} ${camera_size} ${camera_size}" />
        </geometry>
      </visual>
      <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
      ixx="0.0" ixy="0.0" ixz="0.0"
      iyy="0.0" iyz="0.0"
      izz="0.0"/>
      </inertial>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
          <box size="${camera_size*2} ${camera_size} ${camera_size}" />
        </geometry>
      </collision>
    </link>
<gazebo reference="camera_link">
  <sensor name="camera_link_sensor_name" type="depth">
    <update_rate>20</update_rate>
    <camera>
      <horizontal_fov>1.047198</horizontal_fov>
      <image>
        <width>640</width>
        <height>480</height>
        <format>R8G8B8</format>
      </image>
      <clip>
        <near>0.05</near>
        <far>3</far>
      </clip>
    </camera>
    <plugin name="camera_link_controller" filename="libgazebo_ros_openni_kinect.so">
      <baseline>0.2</baseline>
      <alwaysOn>true</alwaysOn>
      <updateRate>1.0</updateRate>
      <cameraName>camera_link_ir</cameraName>
      <imageTopicName>/camera_link/color/image_raw</imageTopicName>
      <cameraInfoTopicName>/camera_link/color/camera_info</cameraInfoTopicName>
      <depthImageTopicName>/camera_link/depth/image_raw</depthImageTopicName>
      <depthImageInfoTopicName>/camera_link/depth/camera_info</depthImageInfoTopicName>
      <pointCloudTopicName>/camera_link/depth/points</pointCloudTopicName>
      <frameName>camera_link</frameName>
      <pointCloudCutoff>0.5</pointCloudCutoff>
      <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
      <distortionK1>0.00000001</distortionK1>
      <distortionK2>0.00000001</distortionK2>
      <distortionK3>0.00000001</distortionK3>
      <distortionT1>0.00000001</distortionT1>
      <distortionT2>0.00000001</distortionT2>
      <CxPrime>0</CxPrime>
      <Cx>0</Cx>
      <Cy>0</Cy>
      <focalLength>0</focalLength>
      <hackBaseline>0</hackBaseline>
    </plugin>
  </sensor>
</gazebo>

      <!-- Joint List Start -->
      
    <!-- Camera_joints -->
   <joint name="world_to_rail" type="fixed">
      <parent link="world"/>
      <child link="camera_rail"/>
      <origin
      xyz="0 0 ${first_wall_h/2}"
      rpy="0 0 0" />
      </joint> 

    <joint name="rail_to_camera" type="revolute">
      <parent link="camera_rail"/>
      <child link="camera_link"/>
      <origin
      xyz="0 0 ${camera_size}"
      rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit lower="-6.27" upper="6.27" effort="22.54" velocity="17.4845"/>
      </joint> 

      
    <!-- Joint List End -->

    <!-- Camera joint transmission list -->
      <transmission name="trans_camera">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rail_to_camera">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor_camera">
      <mechanicalReduction>1</mechanicalReduction>
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </actuator>
      </transmission> 
    <!-- Colos list  -->
  
 <gazebo reference="camera_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo>
        <static>true</static>
    </gazebo>
  
   <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
          <!-- <robotNamespace>/lab_config</robotNamespace> -->
          <!-- <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType> -->
        </plugin>
      </gazebo> 


</robot>

