# Publish all joint states -----------------------------------
/lab_config/joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

  # Position Controllers ---------------------------------------
/lab_config/camera_position_controller:
   type: effort_controllers/JointPositionController
   joint: rail_to_camera
   pid: {p: 100.0, i: 0.01, d: 10.0}